//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Helper
.ServiceTheReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceTheReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Saved", ReplyAction="http://tempuri.org/IService1/SavedResponse")]
        bool Saved(Helper.DTO.EmployeeDTO EmployeeP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Saved", ReplyAction="http://tempuri.org/IService1/SavedResponse")]
        System.Threading.Tasks.Task<bool> SavedAsync(Helper.DTO.EmployeeDTO EmployeeP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Update", ReplyAction="http://tempuri.org/IService1/UpdateResponse")]
        bool Update(Helper.DTO.EmployeeDTO EmployeeP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Update", ReplyAction="http://tempuri.org/IService1/UpdateResponse")]
        System.Threading.Tasks.Task<bool> UpdateAsync(Helper.DTO.EmployeeDTO EmployeeP);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Helper
.ServiceTheReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Helper
.ServiceTheReference.IService1>, Helper
.ServiceTheReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Saved(Helper.DTO.EmployeeDTO EmployeeP) {
            return base.Channel.Saved(EmployeeP);
        }
        
        public System.Threading.Tasks.Task<bool> SavedAsync(Helper.DTO.EmployeeDTO EmployeeP) {
            return base.Channel.SavedAsync(EmployeeP);
        }
        
        public bool Update(Helper.DTO.EmployeeDTO EmployeeP) {
            return base.Channel.Update(EmployeeP);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAsync(Helper.DTO.EmployeeDTO EmployeeP) {
            return base.Channel.UpdateAsync(EmployeeP);
        }
    }
}
